/**
 * Role and Status Constants
 * Centralized definitions to avoid hardcoded strings
 */

const ROLES = {
  ADMIN: 'ADMIN',
  CUSTOMER: 'SHIPPER',
  CARRIER: 'CARRIER',
  VIEWER: 'VIEWER',
  // Legacy
  CUSTOMER_LEGACY: 'customer',
  PARTNER_LEGACY: 'partner'
};

const SHIPMENT_STATUS = {
  AWARDED: 'AWARDED',
  PICKUP_CONFIRMED: 'PICKUP_CONFIRMED',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED',
  CLOSED: 'CLOSED',
  DISPUTED: 'DISPUTED'
};

const CARRIER_VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  SUSPENDED: 'SUSPENDED'
};

const DOCUMENT_TYPE = {
  INSURANCE: 'INSURANCE',
  W9: 'W9',
  AUTHORITY: 'AUTHORITY',
  BOL: 'BOL'
};

const INVOICE_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  DISPUTED: 'DISPUTED'
};

const AUCTION_STATUS = {
  OPEN: 'open',
  CLOSED: 'CLOSED'
};

/**
 * Shipment state machine valid transitions
 */
const VALID_TRANSITIONS = {
  [SHIPMENT_STATUS.AWARDED]: [SHIPMENT_STATUS.PICKUP_CONFIRMED],
  [SHIPMENT_STATUS.PICKUP_CONFIRMED]: [SHIPMENT_STATUS.IN_TRANSIT],
  [SHIPMENT_STATUS.IN_TRANSIT]: [SHIPMENT_STATUS.DELIVERED],
  [SHIPMENT_STATUS.DELIVERED]: [SHIPMENT_STATUS.CLOSED, SHIPMENT_STATUS.DISPUTED],
  [SHIPMENT_STATUS.CLOSED]: [],
  [SHIPMENT_STATUS.DISPUTED]: [SHIPMENT_STATUS.CLOSED]
};

module.exports = {
  ROLES,
  SHIPMENT_STATUS,
  CARRIER_VERIFICATION_STATUS,
  DOCUMENT_TYPE,
  INVOICE_STATUS,
  AUCTION_STATUS,
  VALID_TRANSITIONS
};
